services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
    - "5678:5678"
    environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_DATABASE=n8n
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_USER=n8n
    - DB_POSTGRESDB_PASSWORD=n8n_password
    - DB_POSTGRESDB_SCHEMA=public
    - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
    - TZ=${TZ:-UTC}
    # Uncomment these lines to set up basic authentication
    # - N8N_BASIC_AUTH_ACTIVE=true
    # - N8N_BASIC_AUTH_USER=user
    # - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
    - n8n_data:/home/node/.n8n
    depends_on:
    - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
    - POSTGRES_DB=n8n
    - POSTGRES_USER=n8n
    - POSTGRES_PASSWORD=n8n_password
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  postgres_data:

# docker compose -f devops/docker/n8n.docker-compose.yaml up --build --detach
# docker compose -f devops/docker/n8n.docker-compose.yaml dow