services:
  fastapi-tts-piper-jetson:
    build:
      context: ../../.. # This should point to the root of your project
      dockerfile: devops/docker/jetson/FastAPI.TTS-piper.Dockerfile
    container_name: FastAPI.TTS-piper.Jetson
    runtime: nvidia
    network_mode: host
    shm_size: 8g
    volumes:
    - ../../..:/app # This mounts the entire root directory to /app in the container
    - /tmp/argus_socket:/tmp/argus_socket
    - /etc/enctune.conf:/etc/enctune.conf
    - /etc/nv_tegra_release:/etc/nv_tegra_release
    - /tmp/nv_jetson_model:/tmp/nv_jetson_model
    - /var/run/dbus:/var/run/dbus
    - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/aic/jetson-containers/data:/data
    - /run/jtop.sock:/run/jtop.sock
    devices:
    - /dev/snd
    - /dev/bus/usb
    - /dev/i2c-0
    - /dev/i2c-1
    - /dev/i2c-2
    - /dev/i2c-3
    - /dev/i2c-4
    - /dev/i2c-5
    - /dev/i2c-6
    - /dev/i2c-7
    - /dev/i2c-8
    - /dev/i2c-9
    restart: always
    env_file:
    - ../../../apps/ports.env
    environment:
    - PORT_SVC_TTS_PIPER=${PORT_SVC_TTS_PIPER:-8766}
    ports:
    - "${PORT_SVC_TTS_PIPER:-8766}:${PORT_SVC_TTS_PIPER:-8766}"
    working_dir: /app # Set the working directory to /app

# docker compose -f devops/docker/jetson/FastAPI.TTS-piper.docker-compose.yaml up --build --detach
