services:
  whisper_trt:
    image: dustynv/whisper_trt:r36.3.0
    container_name: whisper_trt
    runtime: nvidia
    network_mode: host
    shm_size: 8g
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
      - /etc/enctune.conf:/etc/enctune.conf
      - /etc/nv_tegra_release:/etc/nv_tegra_release
      - /tmp/nv_jetson_model:/tmp/nv_jetson_model
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/aic/jetson-containers/data:/data
      - /run/jtop.sock:/run/jtop.sock
      - ${HOME}/Dev/Embedded-AI/others/repos:/home/repos
    devices:
      - /dev/snd
      - /dev/bus/usb
      - /dev/i2c-0
      - /dev/i2c-1
      - /dev/i2c-2
      - /dev/i2c-3
      - /dev/i2c-4
      - /dev/i2c-5
      - /dev/i2c-6
      - /dev/i2c-7
      - /dev/i2c-8
      - /dev/i2c-9
    tty: true
    stdin_open: true
    environment:
      - USER_ID=${UID}
      - GROUP_ID=${GID}

# docker compose -f jetson.docker-compose.yaml up -d
# docker compose -f jetson.docker-compose.yaml down