services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'  # API Port
      - '9001:9001'  # Console Port
    environment:
      - MINIO_ROOT_USER=minio-root-user           # Change this to your desired admin username
      - MINIO_ROOT_PASSWORD=minio-root-password    # Change this to your desired admin password
      - MINIO_DEFAULT_BUCKETS=default-bucket:public    # Creates a default bucket on startup
      - MINIO_FORCE_NEW_KEYS=no                   # Set to 'yes' if you want to force new access keys on restart
      # - MINIO_DISTRIBUTED_MODE_ENABLED=no       # Uncomment to enable distributed mode
      # - MINIO_DISTRIBUTED_NODES=minio1,minio2   # Required for distributed mode
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - minio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
    driver: local

networks:
  minio_network:
    driver: bridge

# docker compose -f devops/docker/infra/minio.docker-compose.yaml up -d